---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
# List of labels common to all resources for this deployment
commonLabels:
  app: traefik
# List of resources we are going to kustomize
resources:
- deployment.yaml
- service.yaml
- clusterrolebinding.yaml
- clusterroles.yaml
- serviceaccount.yaml
