---
kind: Service
apiVersion: v1
metadata:
  name: traefik-ingress-service-test
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
    - protocol: TCP
      port: 80
      name: web
  type: LoadBalancer