---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-admin
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - http:
      paths:
      - path: /admin
        backend:
          serviceName: traefik-admin-service
          servicePort: 8080